name: bdh-project
channels:
  - defaults
dependencies:
  - python==3.10.8
  - scikit-learn
  - seaborn
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pytest
  - keras
  - tensorboard
  - tensorflow
  - pip
  - pip:
    - delayed-assert
    